name: CI

# Controls when the action will run.
on: [ push,pull_request ]
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit_test_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 创建JDK 11环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      # Runs a single command using the runners shell
      - name: gradle缓存配置
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: 执行测试
        run: |
          ./gradlew test
  unit_test_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 创建JDK 11环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      # Runs a single command using the runners shell
      - name: gradle缓存配置
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: 执行测试
        run: |
          ./gradlew test
  unit_test_macos:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 创建JDK 11环境
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      # Runs a single command using the runners shell
      - name: gradle缓存配置
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: 执行测试
        run: |
          ./gradlew test
